### ISSUE TITLE
Error when extracing Majora's Mask 3D files using rip_majoras_mask_3d.bat

### ISSUE THREAD

**Issue by dogcreature** [MeltyPlayer/MeltyTool#15]
When attempting to run the provided "rip_majoras_mask_3d.bat" located in "FinModelUtility-main\cli\", the following error is returned:

```universal_model_extractor 1.0.0
Copyright (C) 2023 universal_model_extractor

ERROR(S):
  Verb 'majoras_mask_3d' is not recognized.

  --help       Display this help screen.

  --version    Display version information.

Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at uni.cli.Cli.Main(String[] args)```

**Comment by MeltyPlayer** [comment]
Shoot, looks like I forgot to include command-line support for this in the EXE. I just added support for this https://github.com/MeltyPlayer/FinModelUtility/commit/494cfbde73c2456811ebb278994c6dbe6cf7b4b7.

Majora's Mask is still in the early stages, though, so not a lot of models are working unfortunately.
