### ISSUE TITLE
bmd2fbx not working

### ISSUE THREAD

**Issue by TimmyIsPog** [MeltyPlayer/MeltyTool#17]
When dragging my .bmd file onto bmd2fbx.exe this error appears in the command line
ERROR(S):
  Verb 'C:\Users\(My Name)\Downloads\Frikmin 2\Exported\Piki\orima1.bmd' is not recognized.

  --help       Display this help screen.

  --version    Display version information.

Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at bmd.cli.Args.PopulateFromArgs(String[] args) in R:\Documents\CSharpWorkspace\Pikmin2Utility\FinModelUtility\Bmd2Fbx\src\cli\Args.cs:line 152
   at bmd.cli.Cli.Main(String[] args) in R:\Documents\CSharpWorkspace\Pikmin2Utility\FinModelUtility\Bmd2Fbx\src\cli\Cli.cs:line 9

I have the latest update downloaded (from the zip download under green code button) at the time of making this message.
Thanks in advance.

**Comment by MeltyPlayer** [comment]
I'm not sure why this didn't work at the time, but I've since deleted bmd2fbx and switched to a new approach that goes through the main executable instead. Hopefully this will work for you!
