### ISSUE TITLE
GLTF Export at incorrect scale

### ISSUE THREAD

**Issue by Starkium** [MeltyPlayer/MeltyTool#18]
Just tested the stalchild from oot 3ds and the export was MASSIVE. Fbx seems to be off by 50x, but that's been consistent with all oot 3ds rips I've tested, so that could be an artifact of whatever they authored stuff in. GLTF export is definitely super huge though, you can import to blender and even if I zoom all the way out I only see a foot from the character. 

GLTF scale seems to be off by 5000x, but again that's taking into account the usual oot scale. 

To clarify, If I get an fbx I have to make the scale .02 to be correct, for GLTF it has to be 0.0002.

**Comment by MeltyPlayer** [comment]
As of https://github.com/MeltyPlayer/FinModelUtility/commit/d6f66f53be77672391388455186028f0edbd3ceb, I've added support for configuring scaling on a game-by-game basis. I still need to look into getting GLTF/FBX consistent, though.

**Comment by MeltyPlayer** [comment]
As of https://github.com/MeltyPlayer/FinModelUtility/commit/cb3743b7666f66b80d6e9ebacd826e25c9d7fef7, this should be fixed now!
