### ISSUE TITLE
Camera Controls

### ISSUE THREAD

**Issue by Starkium** [MeltyPlayer/MeltyTool#19]
Would be nice to add a move up and move down mapped to "e" and "q" respectively. Would also be nice to have an auto center camera on object via the f key. Zoom in/zoom out via scroll wheel would also be nice. The current camera starting position should probably be in a someone isometric position, not at 0,0,0, too.

**Comment by MeltyPlayer** [comment]
As of https://github.com/MeltyPlayer/FinModelUtility/commit/d6f66f53be77672391388455186028f0edbd3ceb, the camera starting position is now in a roughly isometric position.

**Comment by Starkium** [comment]
I'll push my pr with the up and down controls then

**Comment by MeltyPlayer** [comment]
I've gone ahead and added support for this in https://github.com/MeltyPlayer/FinModelUtility/commit/bb48768901670d67293ae935b18e2c75aaf0ac96.
