### ISSUE TITLE
(Pikmin 2) Vertex Colors Still Not Ripped Correctly

### ISSUE THREAD

**Issue by Untitled-1-dev** [MeltyPlayer/MeltyTool#21]
I'm attempting to convert the BMD models of the Pikmin's buds and flowers from Pikmin 2, but FinModelUtility isn't converting their vertex colors properly, as seen below. For reference, the green should be a different shade, and the pink should be yellow. 

I was informed a bug like this was supposedly fixed recently, but today I have downloaded the latest source code of FinModelUtility from this GitHub repository, and the bug still occurs.

This bug also occurs with an older version of FinModelUtility that I downloaded 3 days ago, on April 12th.

![image](https://user-images.githubusercontent.com/84742783/232247454-6b3586cc-a590-4904-b844-5c00baa94520.png)
![image](https://user-images.githubusercontent.com/84742783/232247501-67942206-1346-44ec-a943-e8c44cbded84.png)

**Comment by MeltyPlayer** [comment]
I just tested it in the viewer and in Blender, and I think it should be working now:
![image](https://github.com/MeltyPlayer/FinModelUtility/assets/15970939/deccfa0e-bf71-4d10-973e-ded79848cff3)
![image](https://github.com/MeltyPlayer/FinModelUtility/assets/15970939/dd1e9f73-e0a6-4de5-83e9-f5722737ba3b)

Could you take another look and let me know if there's still any issues?

**Comment by Untitled-1-dev** [comment]
I'll take a look when I can, thanks!
