### ISSUE TITLE
Extraction Issue

### ISSUE THREAD

**Issue by Malik177** [MeltyPlayer/MeltyTool#24]
I need help so I install the hacking tool kit exe before doing this. I'm currenty doing luigis mansion 3ds. 
I put the cia rom in the cili/roms folder and after that I run the batch file that is used for it then I get this error
![Screenshot (583)](https://github.com/MeltyPlayer/FinModelUtility/assets/90985970/6caf17eb-bfbc-43f1-977e-438f0538477a)
After that I close the application and I checked out the hakingtoolkit exe filder and the files that got extracted in the hackingtoolkit directory and not in the out folder thats in cili. All the files are bin files.
![Screenshot (584)](https://github.com/MeltyPlayer/FinModelUtility/assets/90985970/2986aa7e-e607-42e6-903b-8ddefe9430d2)
So I thought that since the files are there in that folder I went back to the cili main folder and clicked on the launch ui bat this error message shows up now and then the universal model extractor opens up and no models show up
![Screenshot (585)](https://github.com/MeltyPlayer/FinModelUtility/assets/90985970/3d0037cd-23d8-4e1f-9494-79907a6c4da4)
![Screenshot (586)](https://github.com/MeltyPlayer/FinModelUtility/assets/90985970/850123aa-7ee6-444b-ab84-2bb1deedfd1c)
Even moving the bin files that are in the hackingtoolkit folder into the out folder didn't fix this problem and then I get same error that is displayed in that picture there. What am I doing wrong? I followed the steps again and did this for majoras mask 3d and yet I keep getting the same errors and problems just like with luigis mansion 3d. The roms I got were from different sites but I ran citra to check to see that if they are cia files and they are.

**Comment by MeltyPlayer** [comment]
I've switched from using HackingToolkit9DS to Ctrtool for extracting CIAs, could you give this another try?

**Comment by Malik177** [comment]
alright ill try doing this again when I'm free
