### ISSUE TITLE
Some models in pikmin 1 have animation issue when extracted.

### ISSUE THREAD

**Issue by m0ntgomery2gat0r** [MeltyPlayer/MeltyTool#29]
Mainly with Olimar and the Pikmins, some animations are missing or corrupted, exept for the blue pikmin. I extracted the files from the gamecube US 1.0 version of the game.

**Comment by MeltyPlayer** [comment]
This is just an issue with the file/animation associations being hardcoded, and I was too lazy to get those linked up initially. I've set this up now though, so it should work now!
