### ISSUE TITLE
couldnt find directory for bmd2fbx

### ISSUE THREAD

**Issue by fatpikmin** [MeltyPlayer/MeltyTool#3]
EDIT: i fixed it by reinstalling with the code i have some errors for double dash but as you said in your video its not perfect so i dont mind also should i send in the errors?

Hey man I first didn't see that i could report some stuff also great tool by the way

So im basically having an issue for the directory oft bmd2fbx.

I tried extracting the contents of pikmin 2 but this always happened 

 I cant put an exact code in here because my system translates it to german because i am german but i can just say it because its simple, 
it's just saying that it couldnt find the directory for bmd2fbx i tried reinstalling it but for some reason everytime i do the process the bmd2fbx.exe file gets deleted.

I tried turning off my antivirus but it still didnt work and i dont know why neither the less im just putting a code in here 

also sorry if there is a misunderstanding for the code i tried my best to translate it:

Processing piki_p2_black w/ manual inputs...
The command ""C:\Users\sonja\OneDrive\Desktop\FinModelUtility-main\cli\tools\bmd2fbx\bmd2fbx.exe"" is either misspelled or could not be found

Processing piki_p2_blue w/ manual inputs...
The command ""C:\Users\sonja\OneDrive\Desktop\FinModelUtility-main\cli\tools\bmd2fbx\bmd2fbx.exe""is either misspelled or could not be found

Processing piki_p2_red w/ manual inputs...
The command ""C:\Users\sonja\OneDrive\Desktop\FinModelUtility-main\cli\tools\bmd2fbx\bmd2fbx.exe""is either misspelled or could not be found

Processing piki_p2_white w/ manual inputs...
The command ""C:\Users\sonja\OneDrive\Desktop\FinModelUtility-main\cli\tools\bmd2fbx\bmd2fbx.exe""is either misspelled or could not be found

Processing piki_p2_yellow w/ manual inputs...
The command ""C:\Users\sonja\OneDrive\Desktop\FinModelUtility-main\cli\tools\bmd2fbx\bmd2fbx.exe"" is either misspelled or could not be found

Processing orima1 w/ manual inputs...
The command ""C:\Users\sonja\OneDrive\Desktop\FinModelUtility-main\cli\tools\bmd2fbx\bmd2fbx.exe"" is either misspelled or could not be found

Processing orima3 w/ manual inputs...
The command ""C:\Users\sonja\OneDrive\Desktop\FinModelUtility-main\cli\tools\bmd2fbx\bmd2fbx.exe""is either misspelled or could not be found

Processing syatyou w/ manual inputs...
The command ""C:\Users\sonja\OneDrive\Desktop\FinModelUtility-main\cli\tools\bmd2fbx\bmd2fbx.exe""is either misspelled or could not be found

the system could not find the specified path.
Checking for previously extracted archives.
Done
press any key . . .

**Comment by MeltyPlayer** [comment]
Thanks for reaching out!

**Edit: If you've already fully fixed this issue, then feel free to disregard the rest of this comment. I _am_ interested in hearing about your issues with Mario Kart: Double Dash, though!**

If you're going through bmd2fbx, then it seems like you're using the _legacy version of the .bat scripts, which are significantly older than the newer versions. Could you let me know if the newer versions of the .bat scripts work for you?

If you need to use the _legacy versions but the bmd2fbx.exe keeps disappearing, then I'm fairly certain this _is_ an issue with the antivirus. I've had the same issue on my own computer until I manually disabled quarantining these paths in my antivirus. Which antivirus software do you have on your computer?

**Comment by MeltyPlayer** [comment]
I’ve deleted bmd2fbx, so I’m marking this as complete.
