### ISSUE TITLE
Unable to export most MM3D NPC Actors, Exception is thrown

### ISSUE THREAD

**Issue by dogcreature** [MeltyPlayer/MeltyTool#34]
When trying to export some MM3D NPC actors, the tool throws an exception:

![image](https://github.com/MeltyPlayer/FinModelUtility/assets/81346574/cf2c326c-2896-445d-99aa-5e7e2fa3f190)

The full text of the error is:
[errorLog(1).txt](https://github.com/MeltyPlayer/FinModelUtility/files/13641159/errorLog.1.txt)

Models such as Tingle, Brac, Honey and Darling, Anju, etc are unable to be exported with the skeleton and animations. There are more that are throwing errors, we have documented the ability of the tool to export these models here: [MM3D NPC Export](https://docs.google.com/spreadsheets/d/1CYm89BC_ezkH4HpDolRsxSU6BmX2V7GR6UTQv_Lpv_w/)

**Comment by MeltyPlayer** [comment]
Thanks for documenting this in that spreadsheet! I’ll take a look at this issue once I get a chance.

Might I ask where this documentation is shared, is this in a Discord?

**Comment by dogcreature** [comment]
Right now this documentation is only in Google Sheets, shared between me and my collaborator with the project we're working on. It was just the two of us who worked on this. [I documented all of the MM3D models](https://docs.google.com/spreadsheets/d/1BY35v38UuS974rJpxOTT1YEJRgWl7WeJ4MZAUZ8IBF8/edit#gid=1965571548) and the spreadsheet I linked in the initial post was the result of us testing NPC exports with skeletons and animations.

If you need additional info, I can provide anything needed.

Thanks for the quick reply!

**Comment by MeltyPlayer** [comment]
Sorry for the delay, my computer exploded like a day after responding to this. I was finally able to get it fixed and take a look, this should be fixed now!
