### ISSUE TITLE
Vertex Colors break

### ISSUE THREAD

**Issue by ZachThePillow** [MeltyPlayer/MeltyTool#4]
I imported a few models that use vertex colors exclusively, and the colors are messed up. the best example i can give is the bulborb larva model, it's supposed to have yellow vertex colors, and it's a pink color instead

**Comment by MeltyPlayer** [comment]
Finally figured out what was causing this and fixed it in https://github.com/MeltyPlayer/FinModelUtility/commit/b0cfca576eb660d4a92e774e63527890c182a385!
