### ISSUE TITLE
Add an option to add lighting

### ISSUE THREAD

**Issue by Malik177** [MeltyPlayer/MeltyTool#40]
can you see if you can add an option to add light in the model viewer? the models from majoras mask and oot 3d are all dark and hard to see i will post a picture later

**Comment by Malik177** [comment]
![Screenshot (908)](https://github.com/MeltyPlayer/FinModelUtility/assets/90985970/781c9bbd-73f4-4b8c-b0fe-f4c94a43913d)

**Comment by MeltyPlayer** [comment]
Thanks for filing a bug for this! I just fixed the lighting for CMB, so this should no longer be an issue.
