### ISSUE TITLE
Update error messaging when the ROM is not found.

### ISSUE THREAD

**Issue by aconeishone** [MeltyPlayer/MeltyTool#7]
console thing says this when trying to rip pikmin 2 stuff 

C:\Users\calvi\Documents\pikmin2hacking\FinModelUtility-main\FinModelUtility-main\cli>tools\universal_model_extractor\universal_model_extractor.exe pikmin_2
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at uni.games.ExtractorUtil.ExtractAll[T](IFileBundleGatherer`1 gatherer, IModelLoader`1 loader)
   at uni.games.pikmin_2.Pikmin2Extractor.ExtractAll()
   at uni.cli.Cli.<>c.<Main>b__0_13(Pikmin2Options _)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at uni.cli.Cli.Main(String[] args)

C:\Users\calvi\Documents\pikmin2hacking\FinModelUtility-main\FinModelUtility-main\cli>pause
Press any key to continue . . .

How to fix??? Why do these things never work ughh

**Comment by aconeishone** [comment]
Wait never mind it's working now, I changed the name to pkmn2.gcm like it said, but turns out it had to be "pikmin_2.gcm" yall should really fix that kinda confusing

**Comment by MeltyPlayer** [comment]
Sorry you ran into this issue. As I said in the README, the name needs to be exactly right--I can look into making this a bit clearer in the error messaging.

**Comment by MeltyPlayer** [comment]
I improved the error messaging here in https://github.com/MeltyPlayer/FinModelUtility/commit/4340604c95bfc92a8d604bea5a8643c5ec05fbe4, so it should be clearer if folks run into this issue in the future. Thanks for reporting this!
