### ISSUE TITLE
Add support for NKit ISOs

### ISSUE THREAD

**Issue by matsmikill** [MeltyPlayer/MeltyTool#9]
hi I'm currently trying to extract models from super mario sunshine,
or any other gamecube games, but i get this following error, on the Command Prompt,

 F:\NINTENDO MODELS EXTRACTION TOOLS\FinModelUtility-main\cli>tools\universal_model_extractor\universal_model_extractor.exe super_mario_sunshine
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at uni.games.ExtractorUtil.ExtractAll[T](IFileBundleGatherer`1 gatherer, IModelLoader`1 loader)
   at uni.games.super_mario_sunshine.SuperMarioSunshineExtractor.ExtractAll()
   at uni.cli.Cli.<>c.<Main>b__0_14(SuperMarioSunshineOptions _)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at uni.cli.Cli.Main(String[] args)

F:\NINTENDO MODELS EXTRACTION TOOLS\FinModelUtility-main\cli>pause
Press any key to continue . . .

plus I'm using the newest release of the program,
Thanks,

**Comment by MeltyPlayer** [comment]
I'm not able to recreate this, is there any more information in the error message--for example, a line number?

If not, would you be able to put your Super Mario Sunshine in this website to get the MD5 hash, in case you're using a different ROM from me?
https://emn178.github.io/online-tools/md5_checksum.html

**Comment by matsmikill** [comment]
no that's all it is showing on the command prompt,

hash: 17e31424978cf85c558d66c445ea227e

**Comment by matsmikill** [comment]
And I'm using a .iso file,

**Comment by MeltyPlayer** [comment]
Based on this thread, it sounds like you might be using an NKit ISO (such as the ones from Vimm’s Lair)?
https://www.romhacking.net/forum/index.php?topic=30584.0

If so, I don’t think those are actually compatible with the tools I use to extract the contents of the ROM. That’s something I’ve been meaning to look into at some point, because NKit ISOs are certainly more space efficient.

Can you try downloading another version of Super Mario Sunshine from a different site and give it another try?

**Comment by matsmikill** [comment]
Ok i will try that, but where do you get them from?, do you use iso files or something different,

**Comment by MeltyPlayer** [comment]
An ISO should work, as long as it’s not an NKit ISO and you rename it to ‘super_mario_sunshine.gcm’. 

I’m probably not allowed to suggest any specific sites here, but if you search for “Super Mario Sunshine ROM” or “Super Mario Sunshine ISO” you should be able to find a download somewhere. A working ROM should be over 1GB.

**Comment by matsmikill** [comment]
Ok i think i understand it now, thanks for helping me,
